name 'evenup-mcollective'
version '1.3.0'
author 'Justin Lambert <jlambert@letsevenup.com>'
license 'Apache'
summary 'Manages mcollective.'
description 'Installs, configures, and runs the mcollective service and agents'
project_page 'https://github.com/evenup/evenup-mcollective'
dependency 'evenup/ruby', '>= 1.3.0'
dependency 'evenup/facter', '>= 1.0.0'

